config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :supermarkets

  root 'supermarkets#index'

 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/supermarket.rb
class Supermarket < ApplicationRecord
       


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/supermarkets_controller.rb
class SupermarketsController < ApplicationController

    def index
        if params[:name]
            @supermarkets = Supermarket.where("name ILIKE ? ", "%#{params[:name]}%")
        else
            @supermarkets = Supermarket.all
        end    
        
    end

    def new
        @supermarket = Supermarket.new
    end

    def create
        @supermarket = Supermarket.new(supermarkets_params)

        if @supermarket.save
            redirect_to @supermarket
        else
            render 'new'
        end
    end

    def show
        @supermarket = Supermarket.find(params[:id])
    end

    def edit
        @supermarket = Supermarket.find(params[:id])
    end

    def destroy
        @supermarket = Supermarket.find(params[:id])
        @supermarket.destroy

        redirect_to supermarkets_path
    end



    def update
        @supermarket = Supermarket.find(params[:id])

        if @supermarket.update (supermarkets_params)
            redirect_to @supermarket
        else
            render 'edit'
        end
    end

    private

    def supermarkets_params
        params.require(:supermarket).permit(:name, :no_of_items, :payment_type, :type)
    end

   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/supermarkets_helper.rb
module SupermarketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KEsupermarkets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/supermarkets/_form.html.erb
<%= form_with model: @supermarket, local: true do |form| %>

    <% if @supermarket.errors.any? %>
        <div id="error_explaination">
            <h2>
                <%= pluralize(@supermarket.errors.count, "error") %>
                    prohibited this supermarket from being saved:
            </h2>
            <ul>
                <% @supermarket.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>

        </div>
    <% end %>

        <p>
            <%= form.label :name %>
            <%= form.text_field :name %>
        </p>
        
        <p>
            <%= form.label :no_of_items %>
            <%= form.text_field :no_of_items %>
        </p>

        <p>
            <%= form.label :variation %>
            <%= form.text_field :variation %>
        </p>

        <p>
            <%= form.label :total %>
            <%= form.text_field :total %>
        </p>

        <p>
            <%= form.label :payment_type %>
            <%= form.text_field :payment_type %>
        </p>
        <%= form.submit %>
        
<% end %>

<% link_to 'Back', supermarkets_path %>

app/views/supermarkets/edit.html.erb
<h1>Edit supermarket</h1>

<%= render 'form' %>

<%= link_to 'Back', supermarkets_path %>

app/views/supermarkets/index.html.erb
<h1>Listing of Kenyan Supermarkets</h1>

<%= form_tag(supermarkets_path, method: "get") do %>
    <%= text_field_tag(:name, params[:name]) %>
    <%= submit_tag("Search") %>
<% end %><br>
<%= link_to 'New Supermarket', new_supermarket_path %><br><br>
<table>
    <tr>
        <th>Name</th>
        <th>Number of items</th>
        <th>Variation</th>
        <th>Total in KSH</th>
        <th>Type</th>
        <th colspan= " 2 "></th>
    </tr>

    <% @supermarkets.each do |supermarket| %>
        <tr>
            <td><%= supermarket.name %></td>
            <td><%= supermarket.no_of_items %></td>
            <td><%= supermarket.variation %></td>
            <td><%= supermarket.total %></td>
            <td><%= supermarket.payment_type %></td>
            <td><%= link_to 'Show', supermarket_path(supermarket) %></td>
            <td><%= link_to 'Edit', edit_supermarket_path(supermarket) %></td>
            <td><%= link_to 'Destroy', supermarket_path(supermarket), method: :delete,
            data: {confirm: 'Are you sure?'} %></td>

        </tr>
        
    <% end %>
    <% if @supermarkets.blank? %>
    <strong>Could not find element <%= params[:name] %> </strong>
    <% end %>
</table>

app/views/supermarkets/new.html.erb
<h1>New Supermarket</h1>

<%= render 'form' %>

<%= link_to 'Back', supermarkets_path %>

app/views/supermarkets/show.html.erb
<ul>   
    
        
        <p><strong>Name:</strong>
        <%= @supermarket.name %></p>
        <p><strong>Number of items:</strong>
        <%= @supermarket.no_of_items %></p>
        <p><strong>Variation:</strong>
        <%= @supermarket.variation %></p>
        <p><strong>Total in KSH:</strong>
        <%= @supermarket.total %></p>
        <p><strong>Type:</strong>
        <%= @supermarket.payment_type %></p>
        

</ul>
<%= link_to 'Back', supermarkets_path %>